import type { Project, ProjectWorkspace } from "@/lib/mvp1Types";

const now = new Date().toISOString();

export const demoProject: Project = {
  id: "demo-project",
  name: "山田製作所 DX支援",
  clientName: "山田製作所",
  industry: "製造業",
  description: "MVP-1デザイン確認用。導線フローアニメーションの見本を含むデモ案件",
  memo: null,
  createdAt: now,
  updatedAt: now,
  archivedAt: null,
};

export const emptyWorkspace: ProjectWorkspace = {
  sourceFiles: [],
  sourceChunks: [],
  extractedItems: [],
  nodes: [],
  edges: [],
  suggestions: [],
  aiComments: [],
  aiRuns: [],
  exportJobs: [],
  versions: [],
  viewLayouts: [],
};

export const demoWorkspace: ProjectWorkspace = {
  sourceFiles: [
    {
      id: "source-1",
      projectId: demoProject.id,
      fileName: "company-overview.pdf",
      fileType: "pdf",
      localPath: "/demo/company-overview.pdf",
      fileHash: "demo",
      status: "read",
      metadataJson: "{}",
      chunkCount: 4,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "source-2",
      projectId: demoProject.id,
      fileName: "sales.csv",
      fileType: "csv",
      localPath: "/demo/sales.csv",
      fileHash: "demo",
      status: "read",
      metadataJson: "{}",
      chunkCount: 8,
      createdAt: now,
      updatedAt: now,
    },
  ],
  sourceChunks: [
    {
      id: "chunk-1",
      projectId: demoProject.id,
      sourceFileId: "source-1",
      fileName: "company-overview.pdf",
      chunkIndex: 0,
      contentPath: "/demo/chunk-1.txt",
      contentPreview:
        "保守サービスと既存製造事業を中心に、Web問い合わせと展示会リードから初回商談へつなげている。",
      contentHash: "demo",
      pageNumber: 4,
      sheetName: null,
      rowStart: null,
      rowEnd: null,
      columnStart: null,
      columnEnd: null,
      headingPath: null,
      metadataJson: "{}",
      createdAt: now,
    },
  ],
  extractedItems: [
    {
      id: "item-business",
      projectId: demoProject.id,
      aiRunId: "run-1",
      name: "既存製造事業",
      itemType: "business",
      description: "主要な収益基盤。既存顧客との関係性が強い。",
      confidenceStatus: "confirmed",
      impactScore: 3,
      subjectiveImportance: 3,
      adoptionStatus: "accepted",
      memo: null,
      sources: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "item-service",
      projectId: demoProject.id,
      aiRunId: "run-1",
      name: "保守サービス",
      itemType: "service",
      description: "継続契約につながる提供価値。",
      confidenceStatus: "estimated",
      impactScore: 3,
      subjectiveImportance: 2,
      adoptionStatus: "accepted",
      memo: null,
      sources: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "item-channel",
      projectId: demoProject.id,
      aiRunId: "run-1",
      name: "Web問い合わせ",
      itemType: "channel",
      description: "新規商談の入口。",
      confidenceStatus: "confirmed",
      impactScore: 2,
      subjectiveImportance: 2,
      adoptionStatus: "accepted",
      memo: null,
      sources: [],
      createdAt: now,
      updatedAt: now,
    },
  ],
  nodes: [
    {
      id: "node-business",
      projectId: demoProject.id,
      extractedItemId: "item-business",
      nodeType: "business",
      label: "既存製造事業",
      description: "主要な収益基盤",
      influenceLevel: "3",
      informationRichness: "88",
      confidenceStatus: "confirmed",
      badgesJson: '["財務あり"]',
      positionJson: '{"x":80,"y":130}',
      adoptionStatus: "accepted",
      memo: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "node-channel",
      projectId: demoProject.id,
      extractedItemId: "item-channel",
      nodeType: "channel",
      label: "Web問い合わせ",
      description: "新規商談の入口",
      influenceLevel: "2",
      informationRichness: "72",
      confidenceStatus: "confirmed",
      badgesJson: '["顧客接点強"]',
      positionJson: '{"x":350,"y":80}',
      adoptionStatus: "accepted",
      memo: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "node-touch",
      projectId: demoProject.id,
      extractedItemId: null,
      nodeType: "touchpoint",
      label: "初回商談",
      description: "問い合わせ後の最初の接点",
      influenceLevel: "2",
      informationRichness: "56",
      confidenceStatus: "estimated",
      badgesJson: "[]",
      positionJson: '{"x":625,"y":135}',
      adoptionStatus: "accepted",
      memo: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "node-service",
      projectId: demoProject.id,
      extractedItemId: "item-service",
      nodeType: "service",
      label: "保守サービス",
      description: "継続契約につながる提供価値",
      influenceLevel: "3",
      informationRichness: "76",
      confidenceStatus: "estimated",
      badgesJson: '["AI注目"]',
      positionJson: '{"x":890,"y":130}',
      adoptionStatus: "accepted",
      memo: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "node-data",
      projectId: demoProject.id,
      extractedItemId: null,
      nodeType: "data_source",
      label: "売上CSV",
      description: "継続契約と売上推移の根拠",
      influenceLevel: "1",
      informationRichness: "64",
      confidenceStatus: "needs_review",
      badgesJson: "[]",
      positionJson: '{"x":350,"y":320}',
      adoptionStatus: "accepted",
      memo: null,
      createdAt: now,
      updatedAt: now,
    },
  ],
  edges: [
    {
      id: "edge-1",
      projectId: demoProject.id,
      sourceNodeId: "node-channel",
      targetNodeId: "node-touch",
      edgeType: "normal",
      flowType: "inquiry",
      strength: "normal",
      direction: "forward",
      confidenceStatus: "estimated",
      evidence: "資料から推定",
      note: null,
      label: "問い合わせ",
      adoptionStatus: "accepted",
      priority: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "edge-2",
      projectId: demoProject.id,
      sourceNodeId: "node-touch",
      targetNodeId: "node-service",
      edgeType: "strong",
      flowType: "proposal",
      strength: "strong",
      direction: "forward",
      confidenceStatus: "estimated",
      evidence: "資料から推定",
      note: null,
      label: "提案",
      adoptionStatus: "accepted",
      priority: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "edge-3",
      projectId: demoProject.id,
      sourceNodeId: "node-data",
      targetNodeId: "node-service",
      edgeType: "weak",
      flowType: "data_reference",
      strength: "weak",
      direction: "forward",
      confidenceStatus: "needs_review",
      evidence: "データ連携は要確認",
      note: null,
      label: "データ連携",
      adoptionStatus: "accepted",
      priority: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "edge-4",
      projectId: demoProject.id,
      sourceNodeId: "node-business",
      targetNodeId: "node-channel",
      edgeType: "bottleneck",
      flowType: "awareness",
      strength: "bottleneck",
      direction: "forward",
      confidenceStatus: "estimated",
      evidence: "認知から問い合わせへの転換が詰まっている",
      note: null,
      label: "認知→問い合わせ",
      adoptionStatus: "accepted",
      priority: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "edge-5",
      projectId: demoProject.id,
      sourceNodeId: "node-service",
      targetNodeId: "node-data",
      edgeType: "data_reference",
      flowType: "data_reference",
      strength: "normal",
      direction: "forward",
      confidenceStatus: "needs_review",
      evidence: "売上CSVから保守契約の実績を参照",
      note: null,
      label: "売上参照",
      adoptionStatus: "accepted",
      priority: null,
      createdAt: now,
      updatedAt: now,
    },
  ],
  suggestions: [
    {
      id: "suggestion-follow",
      projectId: demoProject.id,
      aiRunId: "run-2",
      title: "問い合わせ後フォロー導線の整理",
      description: "Web問い合わせから初回商談までの担当、期限、記録先を確認する。",
      priority: "high",
      adoptionStatus: "pending",
      rationale: "顧客接点の詰まりを最初に解消しやすい。",
      relatedNodeIdsJson: '["node-channel","node-touch"]',
      expectedRevenueImpact: "high",
      expectedProfitImpact: "medium",
      costLevel: "low",
      effortLevel: "low",
      timeToImpact: "short",
      confidenceStatus: "estimated",
      impactScore: 82,
      evidence: "問い合わせから商談までの接続が売上入口に近い。",
      memo: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "suggestion-data",
      projectId: demoProject.id,
      aiRunId: "run-2",
      title: "顧客台帳と売上CSVの突合",
      description: "顧客ID、会社名、メールアドレスのどれで紐づくか確認する。",
      priority: "medium",
      adoptionStatus: "pending",
      rationale: "データ資料を施策判断に使える状態にするため。",
      relatedNodeIdsJson: '["node-data","node-service"]',
      expectedRevenueImpact: "medium",
      expectedProfitImpact: "high",
      costLevel: "medium",
      effortLevel: "medium",
      timeToImpact: "mid",
      confidenceStatus: "needs_review",
      impactScore: 68,
      evidence: "売上CSVが継続契約と売上推移の根拠として存在する。",
      memo: null,
      createdAt: now,
      updatedAt: now,
    },
  ],
  aiComments: [
    {
      id: "comment-1",
      projectId: demoProject.id,
      aiRunId: "run-1",
      commentType: "summary",
      title: "現状の全体像",
      body: "Web問い合わせから初回商談、保守サービスへの導線が中心です。",
      confidenceStatus: "estimated",
      createdAt: now,
    },
  ],
  aiRuns: [],
  exportJobs: [],
  versions: [],
  viewLayouts: [
    {
      id: "layout-impact",
      projectId: demoProject.id,
      viewId: "business_impact",
      layoutJson:
        '{"viewId":"business_impact","positions":[{"nodeId":"node-channel","x":360,"y":90},{"nodeId":"node-touch","x":360,"y":220},{"nodeId":"node-service","x":620,"y":180},{"nodeId":"node-data","x":620,"y":350},{"nodeId":"node-business","x":880,"y":170}]}',
      createdAt: now,
      updatedAt: now,
    },
  ],
};
